# Generated by Django 5.2.17 on 2026-10-01 03:19

import checker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_submission_results_ruleskillfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='output_template',
            field=models.FileField(blank=True, upload_to=checker.models.output_template_upload_path),
        ),
    ]
